### ISSUE TITLE
Записная книжка, курсовая.

### ISSUE THREAD

**Issue by MK981** [BasePractice/cpp_oop#1]
Здравствуйте, я студент 1 курса, у меня задание Записная книжка. У меня такой вопрос, при запуске, у меня программа считывает записи из файла, с помощью функции load_from_file и записывается в вектор, как мне сделать поиск по id? Например, чтобы пользователь вводил id(номер) строки и она выводилась на экран, а потом уже выбирается,что с ней делать удалять или редактировать. И еще по поводу удаления, строку из вектора можно удалить с помощью erase, но потом этот вектор обновленный надо снова записать в файл, я делаю это с помощью функции save, но в итоге у меня в файле вместо нормальных строк с информацией о человеке получается "  ;;;;Антон  ", хотя изначально  были через ; имя, фамилия, телефон и тд. Код в текстовом файле прикрепил.
[Код.txt](https://github.com/BasePractice/cpp_oop/files/998762/default.txt)

**Comment by Pastor** [comment]
Добрый день. 

### Ответы

1. У вас метод `remove` удаляет запись исходя из предположения, что как аргумент у вас приходит порядковый номер записи, а не `id` записи. Вы можете сделать хитрее и сделать `id` записи равным порядковому номеру записи и тогда поле `id` вам не нужно. И тогда `remove` у Вас будет работать правильно + к этому, вам не нужен будет поиск по `id`, т.к. он будет позицией в векторе `_records`. Соответственно при выводе списка записей на экран, вы должны будете выводить против каждой записи - индекс в векторе.
2. Повторюсь. Загрузка записей происходит сразу после запуска вашего приложения, а сохранение происходит до его завершения. Более ни сохранять и загружать записи излишне. Удаление и добавление делайте в `RecordCollection`.
3. Проверьте, у вас не везде в коде `case` оканчивается `break`. Получается так, что вы можете получить результат не соответствующий вашим ожиданиям.


### Немного вопросов по коду.
```cpp
class RecordCollection {
public: vector<Record> _records; //Зачем открывать _records???
	int _ids;
```
